/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.HuespedData;
import AccesoADatos.HabitacionData;
import AccesoADatos.TipoDeHabitacionData;
import Entidades.Habitacion;
import Entidades.Huesped;
import Entidades.TipoDeHabitacion;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author viper
 */
public class InfoHabitacion extends javax.swing.JInternalFrame {
private Habitacion habitacion=new Habitacion();

private HabitacionData habitacionData;
private DefaultTableModel modelo;
    /**
     * Creates new form InfoHabitacion
     */
    public InfoHabitacion() {
        initComponents();
         CargarComboBoxTipoHabitacion();
             modelo = (DefaultTableModel) jTabla.getModel();
             habitacionData = new HabitacionData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTipoHabitacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        jcbTipoHabitacion.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbTipoHabitacionPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jcbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoHabitacionPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbTipoHabitacionPopupMenuWillBecomeInvisible
cargarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoHabitacionPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JComboBox<TipoDeHabitacion> jcbTipoHabitacion;
    // End of variables declaration//GEN-END:variables

 private void CargarComboBoxTipoHabitacion() {
        TipoDeHabitacionData tipoData = new TipoDeHabitacionData();
    
        List<TipoDeHabitacion > h = tipoData.listarTipoDeHabitacion();
     for (TipoDeHabitacion tipoDeHabitacion : h) {
            jcbTipoHabitacion.addItem(tipoDeHabitacion);
     }
    
          

        }
    private void ArmarCabecera() {
     
        modelo.addColumn("ID Habitacion");
        modelo.addColumn("ID TipoHabitacion");
        modelo.addColumn("Precio Noche");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Refraccion");

        modelo.addColumn("Estado");
        jTabla.setModel(modelo);

    }
 private void cargarTabla(){
     HabitacionData habitacionData = new HabitacionData();
     List<Habitacion> lista =habitacionData.listarHabitacion();
     for (Habitacion habitacion : lista) 
         modelo.addRow(new Object[]{
             habitacion.getIdHabitacion(),
             habitacion.getIdTipodehabitacion(),
             habitacion.getPrecioNoche(),
             habitacion.getDescripcion(),
             habitacion.isRefaccion(),
             habitacion.isEstado()
         });
         }
                
         
     }



